
package pizzarendeloalkalmazas;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class PizzaRendeloAlkalmazas extends javax.swing.JFrame {

    /**
     * Creates new form PizzaRendeloAlkalmazas
     */
    public PizzaRendeloAlkalmazas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelcim = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdbtn35cm = new javax.swing.JRadioButton();
        rdbtn20cm = new javax.swing.JRadioButton();
        rdbtn45cm = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rdbtnkukorica = new javax.swing.JRadioButton();
        rdbtnsonka = new javax.swing.JRadioButton();
        rdbtnszalami = new javax.swing.JRadioButton();
        lblajandekszosz = new javax.swing.JLabel();
        cbxszosz = new javax.swing.JComboBox<>();
        lblajandekudito = new javax.swing.JLabel();
        cbxudito = new javax.swing.JComboBox<>();
        lblpizzakep = new javax.swing.JLabel();
        labelweboldal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelcim.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        labelcim.setForeground(new java.awt.Color(153, 0, 0));
        labelcim.setText("Pizza Rendelő Alkalmazás");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Mérete"));

        buttonGroup1.add(rdbtn35cm);
        rdbtn35cm.setText("35 cm");

        buttonGroup1.add(rdbtn20cm);
        rdbtn20cm.setText("20 cm");
        rdbtn20cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn20cmActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtn45cm);
        rdbtn45cm.setText("45 cm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rdbtn45cm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtn35cm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtn20cm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbtn20cm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtn35cm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtn45cm)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Feltétek"));

        rdbtnkukorica.setText("Kukorica");
        rdbtnkukorica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnkukoricaActionPerformed(evt);
            }
        });

        rdbtnsonka.setText("Sonka");

        rdbtnszalami.setText("Szalámi");
        rdbtnszalami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnszalamiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rdbtnszalami, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnsonka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnkukorica, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbtnsonka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnszalami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnkukorica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblajandekszosz.setText("1 db Ajándék Szósz:");

        cbxszosz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Csípős", "Ketchup", "BBQ", "Fokhagymás tejföl" }));
        cbxszosz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxszoszActionPerformed(evt);
            }
        });

        lblajandekudito.setText("1 db Ajándék Üdítő:");

        cbxudito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Coca Cola Zero", "Sprite", "Pepsi Zero", "Fanta", "Lipton Citromos Ice Tea" }));
        cbxudito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxuditoActionPerformed(evt);
            }
        });

        lblpizzakep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/pizza2.jpg"))); // NOI18N

        labelweboldal.setText("<html><a href='#'>Látogasd meg a weboldalunkat!</html>");
        labelweboldal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelweboldal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelweboldalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelweboldalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelweboldalMouseExited(evt);
            }
        });

        jButton1.setText("Rendelés véglegesítése");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblajandekszosz)
                            .addComponent(lblajandekudito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxszosz, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxudito, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblpizzakep, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(labelweboldal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(labelcim)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelcim, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblajandekszosz)
                            .addComponent(cbxszosz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblajandekudito)
                            .addComponent(cbxudito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblpizzakep, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelweboldal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnkukoricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnkukoricaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnkukoricaActionPerformed

    private void rdbtnszalamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnszalamiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnszalamiActionPerformed

    private void labelweboldalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelweboldalMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("https://www.donpepe.hu/hu"));
        } catch (IOException ex) {
            Logger.getLogger(PizzaRendeloAlkalmazas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelweboldalMouseClicked

    private void labelweboldalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelweboldalMouseEntered

    }//GEN-LAST:event_labelweboldalMouseEntered

    private void labelweboldalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelweboldalMouseExited

    }//GEN-LAST:event_labelweboldalMouseExited

    private void cbxszoszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxszoszActionPerformed
        String szosz = (String) cbxszosz.getSelectedItem();

        String uzenet = "A kiválasztott ajándék szósz: " + szosz;

        JOptionPane.showMessageDialog(rootPane, uzenet);
    }//GEN-LAST:event_cbxszoszActionPerformed

    private void cbxuditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxuditoActionPerformed
        String udito = (String) cbxudito.getSelectedItem();

        String kiiras = "A kiválasztott ajándék üdítő: " + udito;

        JOptionPane.showMessageDialog(rootPane, kiiras);
    }//GEN-LAST:event_cbxuditoActionPerformed

    private void rdbtn20cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn20cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtn20cmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("A rendelésedet rögzítettük!");
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaRendeloAlkalmazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaRendeloAlkalmazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaRendeloAlkalmazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaRendeloAlkalmazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaRendeloAlkalmazas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxszosz;
    private javax.swing.JComboBox<String> cbxudito;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelcim;
    private javax.swing.JLabel labelweboldal;
    private javax.swing.JLabel lblajandekszosz;
    private javax.swing.JLabel lblajandekudito;
    private javax.swing.JLabel lblpizzakep;
    private javax.swing.JRadioButton rdbtn20cm;
    private javax.swing.JRadioButton rdbtn35cm;
    private javax.swing.JRadioButton rdbtn45cm;
    private javax.swing.JRadioButton rdbtnkukorica;
    private javax.swing.JRadioButton rdbtnsonka;
    private javax.swing.JRadioButton rdbtnszalami;
    // End of variables declaration//GEN-END:variables
}
